[package]
name = "clpi/idl"
version = "0.1.0-alpha.1"
description = "Building a toy lang in zig"
license = "MIT"
repository = "https://github.com/clpi/idl"

[dependencies]

[[module]]
name = "idl"
source = "idl.wasm"
abi = "wasi"

[[command]]
name = "idl"
module = "idl"
