[package]
name = "clpi/dlang"
version = "1.0.0"
description = "Building a toy lang in zig"
license = "MIT"
repository = "https://github.com/clpi/idlang"

[[module]]
name = "dlang"
source = "dlang.wasm"
abi = "wasi"

[[command]]
name = "idl"
module = "idl"
