name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        host:
          [
            ubuntu-latest,
          ]

    runs-on: ${{matrix.host}}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: "0.9.0"

      - run: zig version
      - run: zig env
      - run: zig build -Dbootstrap
      - run: ./zig-out/bin/zigmod ci
      - run: cat deps.zig
      - run: zig build
      - run: ./zig-out/bin/zigmod version
